# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alarm-system
    username: postgres
    password: abc+!@#123

mybatis-plus:
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 自定义redis key
redis:
  database: "our-task-dev"
  key:
    category: "category"
    user: "user"
    task: "task"
    label: "label"
  expire:
    common: 86400 # 24小时
